### PR TITLE
add functionality to reset password

### PR DESCRIPTION
**Pull request by miguelmartinpas**
Add new feature to reset password using 'Piksel IdM Reset Password Endpoint for initiating a password reset'

https://identity-use1shared.sequoia.piksel.com/docs/routes/pauth-reset-password

### CODE REVIEW

**Comment by gerbilsinspace** [comment]
I'd make this a minor bump, it's a functional change rather than a bug fix.

**Comment by miguelmartinpas** [comment]
Sure, it is a new feature I didn't writte anything about bug

Regarding the second step. I don't have any specification at the moment. I am not sure if the system will send a notification like a email with a new password or it will do other thing... 

My ticket only need to show a button to reset password for each user in a list ad catch 204 or other error code

**Comment by jamiedust** [comment]
Could you also bump the minor version number in the package.json and add an entry to the changelog?

**Comment by miguelmartinpas** [comment]
the current version is 1.13.1 so should change to 1.13.2, right?

regarding my requirements for this ticket are only call to reset action and show the response. Only that

**Comment by jamiedust** [comment]
So, I am happy to accept this, however I am not sure of the process involved in publishing a new version to npm (or if I even have access). So we should probably wait for @gerbilsinspace to merge it.

**Pull request merged**
